# "service" is the name of this project. This will also be added to your AWS resource names.
service: test-serverless

provider:
  name: aws
  runtime: nodejs22.x
  httpApi:
    authorizers:
      customAuthorizer:
        type: request
        functionName: authorizerFunc
        identitySource:
          - $request.header.Auth
          - $request.header.Authorization

functions: ${file(./src/serverless-config/dev/functions.yml)}

plugins:
  - serverless-offline
